targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
          - example/**.dart
          - example/**/**.dart
        options:
          dart2js_args:
            - --minify
            - --fast-startup