name: trackasia_gl_dart
version: 0.2.2
description: trackasia-gl wrapper for Dart. Library to use trackasia GL JS in
  your web Dart projects. Forked from
  https://github.com/andrea689/mapbox-gl-dart
homepage: https://github.com/track-asia/trackasia-gl-dart
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.4.5
  build_web_compilers: ^4.0.3
